### ISSUE TITLE
 "Fleetsave" can not Automatic filling of resources???

### ISSUE THREAD

**Issue by gwlogs** [Rivenscryr/AntiGameReborn#23]
I found that "Fleetsave" can not be automatic filling of resources???
Every time, I choose Fleetsave, I choose task colon, and finally, before launching the fleet, it will not automatically fill up the resources.

**Comment by Rivenscryr** [comment]
This is intended behaviour. You need click "Fill all resources" or "Fill most resources" before sending the fleet. Otherwise fleetsaving would be too automated.
